### ISSUE TITLE
GDAL_jll broke – uses LERC_jll without declaring it

### ISSUE THREAD

**Issue by eschnett** [JuliaGeo/GDAL.jl#179] opened 2024-10-08 14:06 UTC
Yesterday I created a new version of Libtiff_jll that uses LERC_jll, updating from LERC 3 to LERC 4.

This morning I see that GDAL_jll is broken. I see the error message
```
ERROR: LoadError: InitError: could not load library "/Users/eschnett/.julia/artifacts/1337ee940f233626adea175588d755d2f70a802f/lib/libgdal.35.dylib"
dlopen(/Users/eschnett/.julia/artifacts/1337ee940f233626adea175588d755d2f70a802f/lib/libgdal.35.dylib, 0x0001): Library not loaded: @rpath/libLerc.dylib
```

It is possible/likely that GDAL_jll depends on LERC_jll, but doesn't declare so. It now expects LERC_jll version 3, but that is not available any more.

If so, the solution would be to either add a compat bound for GDAL_jll, restricting Libtiff_jll to `~4.6`, or to release a new version of GDAL_jll that either doesn't use LERC or explicitly delcares this dependency.

**Comment by visr** [comment] 2024-10-08 15:08
I guess LERC was just picked up automatically since it was found since libtiff has it as a dependency:

> Control whether to use LERC. Defaults to ON when LERC is found.

From https://gdal.org/en/latest/development/building_from_source.html#lerc

> LERC compression is also available when building GDAL against external libtiff >= 4.3.0, built itself against https://github.com/esri/lerc

https://gdal.org/en/latest/drivers/raster/gtiff.html

So I guess it would be best to explicitly declare the LERC dependency.

**Comment by visr** [comment] 2024-10-08 15:14
This breakage doesn't affect Windows. Is `add LERC_jll@3` enough for you as a workaround?

**Comment by arlowhite** [comment] 2024-10-09 01:36
confirmed that LERC_jll 3 works, but 4 does not. So may want to compat or pin
`add LERC_jll@3`
`compat LERC_jll 3`

**Comment by tpoisot** [comment] 2024-10-09 02:27
The fix of adding `LERC_jll@3` works on Linux - but this should be handled by `GDAL.jl` directly

**Comment by eschnett** [comment] 2024-10-09 14:32
I think it should be handled by `GDAL_jll.jl`, not `GDAL.jl`, either by adding (after the fact) the missing compat bound, or by releasing a new version with an explicit dependency on `LERC_jll.jl`.

**Comment by visr** [comment] 2024-10-09 20:54
I submitted the (hopefully) quick fix https://github.com/JuliaPackaging/Yggdrasil/pull/9588 to add a LERC v3, and https://github.com/JuliaPackaging/Yggdrasil/pull/9586 and https://github.com/JuliaPackaging/Yggdrasil/pull/9587 as the way forward, such that we also become compatible with the latest PROJ build again.

**Comment by ViralBShah** [comment] 2024-10-10 01:51
Thanks guys. I just found this myself with 1.11, and great to see a fix is almost in place.

**Comment by visr** [comment] 2024-10-10 18:19
Fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/9588 as shown by https://github.com/JuliaGeo/GDAL.jl/pull/181.

**Closed by visr** 2024-10-10 18:19 UTC
Labels: build
